# Fundamentals
In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:
* Introduction to tensors;
* Getting information from tensors;
* Manipulating tensors;
* Tensors & NumPy;
* Using @tf.function (a way to speed up regular Python functions);
* Using GPUs with Tensorflow (or TPUs);
* Exercises to follow along.

In [1]:
# Import Tensorflow
import tensorflow as tf

In [2]:
print(tf.__version__)

2.9.2


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of the vector
vector.ndim

1

In [10]:
# Create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [15]:
# Creating a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 1, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10,  1, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3

What we've created so far:
* Scalar: a single numnber;
* vector: a number with direction (e.g. wind speed and direction);
* Matrix: a 2-dimensional array of numbers;
* Tensor: a n-dimensional array of numbers (when n can be any number, a 0-dimesional tensor is a scalar, a 1-dimensional tensor is a vector, and so on).