<a href="https://colab.research.google.com/github/fabiodemo/Tensorflow-Developer-Certificate/blob/main/Deep%20Learning%20and%20TensorFlow%20Fundamentals/00_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🛠 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [2]:
import tensorflow as tf

In [12]:
# 1
A = tf.constant([10, 20, 30])
B = tf.constant([[10, 20],
                 [30, 40]])
C = tf.constant([[[12, 40, 20],
                  [16, 45, 20],
                  [40, 60, 89]]])
A, B, C

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>,
 TensorShape([3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[12, 40, 20],
         [16, 45, 20],
         [40, 60, 89]]], dtype=int32)>)

In [15]:
# 2
print('A dimension: ', A.ndim)
print('A shape: ', A.shape)
print('A size: ', tf.size(A))
print('B dimension: ', B.ndim)
print('B shape: ', B.shape)
print('B size: ', tf.size(B))
print('C dimension: ', C.ndim)
print('C shape: ', C.shape)
print('C size: ', tf.size(C))

A dimension:  1
A shape:  (3,)
A size:  tf.Tensor(3, shape=(), dtype=int32)
B dimension:  2
B shape:  (2, 2)
B size:  tf.Tensor(4, shape=(), dtype=int32)
C dimension:  3
C shape:  (1, 3, 3)
C size:  tf.Tensor(9, shape=(), dtype=int32)


In [19]:
# 3
import numpy as np
D = tf.constant(np.random.randint(3, 500, size=1500), shape=(5,300))
E = tf.constant(np.random.randint(3, 500, size=1500), shape=(5,300))
D, E

(<tf.Tensor: shape=(5, 300), dtype=int64, numpy=
 array([[109,  86, 382, ..., 310,  47, 198],
        [163, 238,  60, ..., 138, 399, 431],
        [306,   9, 229, ..., 223, 113, 496],
        [246, 199, 103, ..., 459, 420, 210],
        [414, 497, 399, ..., 358,  42, 288]])>,
 <tf.Tensor: shape=(5, 300), dtype=int64, numpy=
 array([[ 33, 363, 356, ..., 101, 438, 374],
        [463, 411, 123, ..., 418, 220, 180],
        [450, 263, 320, ..., 300,  21, 427],
        [174, 135,  14, ..., 440, 389,   9],
        [412, 202,  69, ..., 447,  73, 193]])>)

In [24]:
# 4
tf.reshape(D, shape=(300,5)) @ E

<tf.Tensor: shape=(300, 300), dtype=int64, numpy=
array([[296027, 231647, 180052, ..., 333535, 209330, 232806],
       [499880, 367991, 215205, ..., 502539, 224097, 320623],
       [389002, 298863, 142773, ..., 420643, 209768, 221546],
       ...,
       [456791, 354026, 247068, ..., 471723, 248142, 343852],
       [525200, 435664, 253345, ..., 580121, 336800, 363440],
       [512025, 469487, 311106, ..., 481567, 293250, 417278]])>

In [23]:
# 5
tf.tensordot(tf.transpose(D), E, axes=1)

<tf.Tensor: shape=(300, 300), dtype=int64, numpy=
array([[430138, 303876, 188783, ..., 464241, 215944, 282884],
       [356472, 258662,  99849, ..., 420589, 203909, 176559],
       [325746, 318056, 245625, ..., 356035, 254519, 329385],
       ...,
       [401836, 362178, 229822, ..., 517880, 375508, 309226],
       [327522, 275953, 110747, ..., 409003, 277185, 149535],
       [584483, 465989, 305033, ..., 570092, 294674, 420898]])>

In [28]:
224*224*3

150528

In [34]:
# 6 224, 224, 3
# D = tf.constant(np.random.randint(3, 500, size=1500), shape=(5,300))
F = tf.constant(np.random.randint(0, 1, size=150528), shape=(224, 224, 3))
F

<tf.Tensor: shape=(224, 224, 3), dtype=int64, numpy=
array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])>

In [31]:
# 7
tf.reduce_max(F, axis=1)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]

In [45]:
# 8 
G_squeezed = tf.squeeze(G)
G_squeezed


<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.05521214, 0.5694376 , 0.23994994],
        [0.11486828, 0.21533477, 0.22755659],
        [0.730096  , 0.48880017, 0.70787156],
        ...,
        [0.7717689 , 0.05121017, 0.8336891 ],
        [0.11924863, 0.30839086, 0.7639426 ],
        [0.67709124, 0.3571179 , 0.2749381 ]],

       [[0.2884332 , 0.7315296 , 0.18192625],
        [0.5731095 , 0.68790555, 0.8454919 ],
        [0.80096817, 0.02044475, 0.5883293 ],
        ...,
        [0.6277685 , 0.35496294, 0.12868834],
        [0.627277  , 0.9957205 , 0.8948965 ],
        [0.7149048 , 0.47082448, 0.8201505 ]],

       [[0.9022447 , 0.85468256, 0.09715247],
        [0.9386722 , 0.05493188, 0.7987038 ],
        [0.90322554, 0.87712336, 0.9150202 ],
        ...,
        [0.3253988 , 0.22240663, 0.56394756],
        [0.47095156, 0.472937  , 0.7251054 ],
        [0.41310108, 0.1502018 , 0.5899668 ]],

       ...,

       [[0.81925154, 0.62741673, 0.2908435 ],
        [0.05

In [55]:
# 9
H = tf.Variable([0.06399345, 0.16117096, 0.2023902 , 0.9479101 , 0.51758206,
       0.8455838 , 0.7279105 , 0.7041055 , 0.27062988, 0.6860987 ])
H.shape

TensorShape([10])

In [64]:
# 10
tf.one_hot(tf.cast(H, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### 📖 00. TensorFlow Fundamentals Extra-curriculum 

* Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.
