In [2]:
import numpy as np

  ## DataTypes & Attributes

Numpy's main datatype is ndarray

In [3]:
a1 = np.array([1, 2, 3])
a1 = np.array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2, 3],[4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Shape of the arrays

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

Number of dimensions

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

Create a DataFrame from a Numpy array

In [15]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
sample_array = np.array((1, 2, 3))
sample_array.dtype

dtype('int64')

Create array of ones

In [19]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [22]:
zeros = np.zeros((5, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Random array

In [23]:
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[5, 3, 8],
       [2, 6, 2],
       [0, 0, 2],
       [5, 8, 8],
       [2, 4, 3]])

Random array of floats between 0 and 1

In [24]:
np.random.random((5, 3))

array([[0.52525155, 0.64061389, 0.02592881],
       [0.63401146, 0.4940918 , 0.84637067],
       [0.76376936, 0.17902157, 0.58235777],
       [0.74797144, 0.61119759, 0.57928477],
       [0.81475393, 0.04754037, 0.39034152]])

In [25]:
np.random.rand(5, 3)

array([[0.36664603, 0.83310823, 0.87828632],
       [0.70063069, 0.07794645, 0.12820794],
       [0.69101352, 0.17061908, 0.64425425],
       [0.54161056, 0.43389174, 0.78417231],
       [0.32032955, 0.40399066, 0.48472936]])

Setting the seed to generate the same pseudo-random numbers

In [26]:
np.random.seed(0)

np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [27]:
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [28]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5,3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

Finding unique numbers in array

In [29]:
np.unique(df)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [31]:
np.unique(random_array)

array([0, 2, 3, 4, 5, 6, 8])

## Viewing arrays and matrices

In [32]:
a1

array([1, 2, 3])

In [33]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1[0]

1

In [37]:
a2[0]

array([1., 2., 3.])

In [39]:
a2.shape

(2, 3)

In [38]:
a2[0][0]

1.0

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [45]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [46]:
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]])

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

Got the  first 4 numbers of the inner most arrays

In [49]:
a4[:, :, :, :3]

array([[[[8, 8, 2],
         [0, 8, 8],
         [2, 8, 4],
         [4, 3, 6]],

        [[0, 8, 5],
         [9, 6, 5],
         [8, 0, 4],
         [5, 7, 8]],

        [[2, 8, 6],
         [1, 6, 8],
         [2, 3, 6],
         [5, 7, 0]]],


       [[[6, 5, 8],
         [9, 7, 5],
         [5, 3, 3],
         [9, 9, 7]],

        [[3, 9, 7],
         [1, 2, 2],
         [5, 8, 4],
         [5, 5, 0]],

        [[1, 0, 3],
         [4, 4, 0],
         [7, 3, 2],
         [2, 1, 4]]]])

In [50]:
a4[:, :, :, :1]

array([[[[8],
         [0],
         [2],
         [4]],

        [[0],
         [9],
         [8],
         [5]],

        [[2],
         [1],
         [2],
         [5]]],


       [[[6],
         [9],
         [5],
         [9]],

        [[3],
         [1],
         [5],
         [5]],

        [[1],
         [4],
         [7],
         [2]]]])

## Manipulating and comparing arrays

Arithmetic

In [52]:
a1

array([1, 2, 3])

In [54]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [55]:
a1 + ones

array([2., 3., 4.])

In [56]:
a1- ones

array([0., 1., 2.])

In [57]:
a1 * ones

array([1., 2., 3.])

In [58]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [ ]:
a1 / a2

array([[1.        , 1.        , 1.        ],
       [0.25      , 0.4       , 0.46153846]])

In [87]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [63]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [60]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

a = np.array([1.0, 2.0, 3.0])

Broadcasting 

How to reshape a2 to be compatible with a3

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [85]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.5]]])

In [86]:
a2.reshape(2, 3, 1) * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [88]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [89]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [90]:
np.add(a1, ones)

array([2., 3., 4.])

In [91]:
a2 % 2

array([[1. , 0. , 1. ],
       [0. , 1. , 0.5]])