In [6]:
import numpy as np

  ## DataTypes & Attributes

Numpy's main datatype is ndarray

In [7]:
a1 = np.array([1, 2, 3])
a1 = np.array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2, 3],[4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [10]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Shape of the arrays

In [12]:
a1.shape

(3,)

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

Number of dimensions

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

Create a DataFrame from a Numpy array

In [19]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating Arrays

In [20]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int64')

In [22]:
sample_array = np.array((1, 2, 3))
sample_array.dtype

dtype('int64')

Create array of ones

In [23]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [26]:
zeros = np.zeros((5, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Random array

In [27]:
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[2, 9, 8],
       [2, 7, 8],
       [5, 1, 7],
       [9, 5, 9],
       [1, 1, 4]])

Random array of floats between 0 and 1

In [28]:
np.random.random((5, 3))

array([[0.28492922, 0.60110696, 0.78452253],
       [0.67675031, 0.58757912, 0.10460273],
       [0.12174114, 0.14117961, 0.95357557],
       [0.69314297, 0.65844846, 0.49574207],
       [0.13705637, 0.82938812, 0.56114967]])

In [29]:
np.random.rand(5, 3)

array([[0.15215781, 0.54683049, 0.50790666],
       [0.61186576, 0.12834413, 0.02517448],
       [0.52386105, 0.54772447, 0.14844233],
       [0.09970929, 0.8339421 , 0.85090322],
       [0.71304921, 0.58414469, 0.47801915]])

Setting the seed to generate the same pseudo-random numbers

In [30]:
np.random.seed(0)

np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [31]:
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [32]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5,3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

Finding unique numbers in array

In [33]:
np.unique(df)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [35]:
np.unique(random_array)

array([1, 2, 4, 5, 7, 8, 9])

## Viewing arrays and matrices

In [36]:
a1

array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a1[0]

1

In [40]:
a2[0]

array([1., 2., 3.])

In [41]:
a2.shape

(2, 3)

In [42]:
a2[0][0]

1.0

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [46]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [47]:
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

Got the  first 4 numbers of the inner most arrays

In [49]:
a4[:, :, :, :3]

array([[[[6, 7, 7],
         [5, 9, 8],
         [3, 0, 3],
         [2, 3, 8]],

        [[3, 3, 7],
         [9, 9, 0],
         [3, 2, 7],
         [0, 4, 5]],

        [[8, 4, 1],
         [8, 1, 1],
         [9, 3, 6],
         [0, 3, 5]]],


       [[[4, 6, 4],
         [4, 4, 8],
         [7, 5, 5],
         [5, 9, 3]],

        [[0, 1, 2],
         [0, 3, 2],
         [5, 9, 0],
         [2, 9, 2]],

        [[2, 3, 4],
         [9, 1, 4],
         [2, 3, 0],
         [0, 6, 3]]]])

In [50]:
a4[:, :, :, :1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

## Manipulating and comparing arrays

Arithmetic

In [51]:
a1

array([1, 2, 3])

In [52]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [53]:
a1 + ones

array([2., 3., 4.])

In [54]:
a1- ones

array([0., 1., 2.])

In [55]:
a1 * ones

array([1., 2., 3.])

In [56]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [57]:
a1 / a2

array([[1.        , 1.        , 1.        ],
       [0.25      , 0.4       , 0.46153846]])

In [58]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [59]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [60]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

a = np.array([1.0, 2.0, 3.0])

Broadcasting 

How to reshape a2 to be compatible with a3

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.5]]])

In [ ]:
a2.reshape(2, 3, 1) * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [ ]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [ ]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [ ]:
np.add(a1, ones)

array([2., 3., 4.])

In [ ]:
a2 % 2

array([[1. , 0. , 1. ],
       [0. , 1. , 0.5]])

### Aggregation

Performing the same operation on a number of things.

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [ ]:
sum(listy_list)

6

In [61]:
sum(a1)

6

In [62]:
np.sum(a1)

6

Use Python's methods on Python datatypes (`sum()`)

Use Numpy's methods on NumPy arrays (`np.sum()`)

In [64]:
massive_array = np.random.random(10000000)
massive_array.size

10000000

In [65]:
massive_array[:100]

array([0.16475883, 0.65916044, 0.24111538, 0.6716312 , 0.12248405,
       0.72298915, 0.60153271, 0.45208079, 0.15555283, 0.85879226,
       0.34115809, 0.25051878, 0.4822044 , 0.84233098, 0.61060318,
       0.63697443, 0.3989384 , 0.42117766, 0.68218055, 0.22674785,
       0.70943877, 0.24668364, 0.89125977, 0.05891762, 0.11173808,
       0.39580508, 0.69443176, 0.11944159, 0.9333064 , 0.76218089,
       0.34387338, 0.07910152, 0.65976338, 0.79354477, 0.72299258,
       0.31188512, 0.62432011, 0.83424031, 0.99890176, 0.82113779,
       0.59665819, 0.34460464, 0.61670776, 0.79334285, 0.77823891,
       0.60604678, 0.53735454, 0.94921068, 0.9649991 , 0.76370599,
       0.61807164, 0.67684207, 0.75371233, 0.77279737, 0.67810494,
       0.48143139, 0.36619233, 0.67231693, 0.6872    , 0.95682063,
       0.03624294, 0.47775347, 0.68651265, 0.31162055, 0.9196282 ,
       0.85243476, 0.06305651, 0.93223409, 0.21201059, 0.7911367 ,
       0.10656012, 0.22712116, 0.61365375, 0.23630237, 0.62890

In [66]:
%timeit sum(massive_array)

1.07 s ± 18.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [67]:
%timeit np.sum(massive_array)

4.63 ms ± 152 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [68]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

### Statistical functions

In [69]:
np.mean(a2)

3.5833333333333335

In [70]:
np.max(a2)

6.5

In [71]:
np.min(a2)

1.0

In [72]:
np.std(a2)

1.8352262954621035

In [74]:
np.sqrt(np.var(a2))

1.8352262954621035

In [73]:
np.var(a2)

3.368055555555556